//
//  UIColor+PIAdditions.swift
//
//  Generated by Zeplin on 3/15/17.
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//

import UIKit

// Color palette

extension UIColor {
    class var piCommonMealGradientStartColor: UIColor {
        return UIColor(red: 23.0 / 255.0, green: 204.0 / 255.0, blue: 188.0 / 255.0, alpha: 1.0)
    }

    class var piCommonMealTableCellIndicatorColor: UIColor {
        return UIColor(red: 53.0 / 255.0, green: 164.0 / 255.0, blue: 234.0 / 255.0, alpha: 1.0)
    }

    class var piTestMealTableCellIndicatorColor: UIColor {
        return UIColor(red: 14.0 / 255.0, green: 195.0 / 255.0, blue: 180.0 / 255.0, alpha: 1.0)
    }

    class var piDashboardDateHeaderTextColor: UIColor {
        return UIColor(red: 16.0 / 255.0, green: 17.0 / 255.0, blue: 34.0 / 255.0, alpha: 1.0)
    }

    class var piTestMealButtonGradientStartColor: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 204.0 / 255.0, blue: 121.0 / 255.0, alpha: 1.0)
    }

    class var piTestMealButtonGradientFinishColor: UIColor {
        return UIColor(red: 229.0 / 255.0, green: 135.0 / 255.0, blue: 73.0 / 255.0, alpha: 1.0)
    }

    class var piCommonMealGradientFinishColor: UIColor {
        return UIColor(red: 26.0 / 255.0, green: 162.0 / 255.0, blue: 194.0 / 255.0, alpha: 1.0)
    }

    class var piDarkSkyBlue: UIColor {
        return UIColor(red: 49.0 / 255.0, green: 175.0 / 255.0, blue: 232.0 / 255.0, alpha: 1.0)
    }

    class var piCornflower: UIColor {
        return UIColor(red: 120.0 / 255.0, green: 89.0 / 255.0, blue: 251.0 / 255.0, alpha: 1.0)
    }

    class var piBackgroundBlue: UIColor {
        return UIColor(red: 43.0 / 255.0, green: 166.0 / 255.0, blue: 227.0 / 255.0, alpha: 1.0)
    }

    class var piBluish: UIColor {
        return UIColor(red: 40.0 / 255.0, green: 143.0 / 255.0, blue: 189.0 / 255.0, alpha: 1.0)
    }

    class var piBlueyPurple: UIColor {
        return UIColor(red: 97.0 / 255.0, green: 72.0 / 255.0, blue: 203.0 / 255.0, alpha: 1.0)
    }

    class var piGreyblue: UIColor {
        return UIColor(red: 110.0 / 255.0, green: 141.0 / 255.0, blue: 177.0 / 255.0, alpha: 1.0)
    }

    class var piGreyblueTwo: UIColor {
        return UIColor(red: 136.0 / 255.0, green: 157.0 / 255.0, blue: 197.0 / 255.0, alpha: 1.0)
    }

    class var piDreBlue: UIColor {
        return UIColor(red: 112.0 / 255.0, green: 130.0 / 255.0, blue: 175.0 / 255.0, alpha: 1.0)
    }

    class var piDenim: UIColor {
        return UIColor(red: 61.0 / 255.0, green: 92.0 / 255.0, blue: 128.0 / 255.0, alpha: 1.0)
    }

    class var piWhite: UIColor {
        return UIColor(white: 255.0 / 255.0, alpha: 1.0)
    }

    class var piBlack16: UIColor {
        return UIColor(white: 49.0 / 255.0, alpha: 0.16)
    }

    class var piPaleGrey: UIColor {
        return UIColor(red: 245.0 / 255.0, green: 250.0 / 255.0, blue: 252.0 / 255.0, alpha: 1.0)
    }

    class var piPaleGreyTwo: UIColor {
        return UIColor(red: 238.0 / 255.0, green: 240.0 / 255.0, blue: 241.0 / 255.0, alpha: 1.0)
    }

    class var piSkyBlue: UIColor {
        return UIColor(red: 81.0 / 255.0, green: 201.0 / 255.0, blue: 255.0 / 255.0, alpha: 1.0)
    }

    class var piCornflowerTwo: UIColor {
        return UIColor(red: 108.0 / 255.0, green: 123.0 / 255.0, blue: 253.0 / 255.0, alpha: 1.0)
    }

    class var piTopaz: UIColor {
        return UIColor(red: 14.0 / 255.0, green: 195.0 / 255.0, blue: 179.0 / 255.0, alpha: 1.0)
    }

    class var piTopaz40: UIColor {
        return piTopaz.withAlphaComponent(0.4)
    }

    class var piTurquoise: UIColor {
        return UIColor(red: 10.0 / 255.0, green: 187.0 / 255.0, blue: 171.0 / 255.0, alpha: 1.0)
    }

    class var piLightOrange: UIColor {
        return UIColor(red: 255.0 / 255.0, green: 168.0 / 255.0, blue: 75.0 / 255.0, alpha: 1.0)
    }

    class var piLightOrange40: UIColor {
        return piLightOrange.withAlphaComponent(0.4)
    }

    class var piLightBlueGrey: UIColor {
        return UIColor(red: 172.0 / 255.0, green: 198.0 / 255.0, blue: 232.0 / 255.0, alpha: 1.0)
    }

    class var piLightBlueGreyTwo: UIColor {
        return UIColor(red: 223.0 / 255.0, green: 232.0 / 255.0, blue: 243.0 / 255.0, alpha: 1.0)
    }

    class var piGreyishBlue: UIColor {
        return UIColor(red: 103.0 / 255.0, green: 120.0 / 255.0, blue: 166.0 / 255.0, alpha: 1.0)
    }

    class var piDusk: UIColor {
        return UIColor(red: 79.0 / 255.0, green: 94.0 / 255.0, blue: 130.0 / 255.0, alpha: 1.0)
    }

    class var piMetallicBlue: UIColor {
        return UIColor(red: 86.0 / 255.0, green: 102.0 / 255.0, blue: 141.0 / 255.0, alpha: 1.0)
    }

    class var piAlmostWhite: UIColor {
        return UIColor(white: 248.0 / 255.0, alpha: 1.0)
    }

    class var piBlueyGrey: UIColor {
        return UIColor(red: 131.0 / 255.0, green: 150.0 / 255.0, blue: 174.0 / 255.0, alpha: 1.0)
    }

    class var piLightBlueGreyThree: UIColor {
        return UIColor(red: 172.0 / 255.0, green: 197.0 / 255.0, blue: 231.0 / 255.0, alpha: 1.0)
    }

    class var piPaleGreyThree: UIColor {
        return UIColor(red: 225.0 / 255.0, green: 232.0 / 255.0, blue: 240.0 / 255.0, alpha: 1.0)
    }

    class var piDarkishPink: UIColor {
        return UIColor(red: 231.0 / 255.0, green: 78.0 / 255.0, blue: 118.0 / 255.0, alpha: 1.0)
    }

    class var piErrorBackground: UIColor {
        return UIColor(red: 231.0 / 255.0, green: 78.0 / 255.0, blue: 118.0 / 255.0, alpha: 1.0)
    }
}
