#platform :ios, '9.0'

target 'MealTrackingPilot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealTrackingPilot
  pod 'Intrepid'
  pod 'Intrepid/Rx'
  pod 'KeychainAccess'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm'
  #pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'AlamofireImage', '~> 4.0.0-beta.2'
  pod 'TPKeyboardAvoiding'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'MealTrackingPilotTests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'RxBlocking'
    pod 'RxTest'
  end

  target 'MealTrackingPilotUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
