platform :ios, '9.0'

target 'MealTrackingPilot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MealTrackingPilot
  pod 'Intrepid', '~> 0.9.0'
  pod 'Intrepid/Rx', '~> 0.9.0'
  pod 'KeychainAccess'
  pod 'RealmSwift'
  pod 'RxSwift', '~> 4.0'
  pod 'RxCocoa', '~> 4.0'
  pod "RxRealm"
  pod 'APIClient', :git => 'https://github.com/IntrepidPursuits/prefab-api-client.git', :branch => 'max/Swift-4'
  pod 'SwiftDate', '~> 4.4.1'
  pod 'AlamofireImage', '~> 3.3'
  pod 'PickerView', :git => 'https://github.com/MaxHasADHD/PickerView', :branch => 'steve/meal-tracker', :inhibit_warnings => true
  pod 'TPKeyboardAvoiding'
  pod 'ReverseExtension', :git => 'https://github.com/IntrepidPursuits/ReverseExtension', :branch => 'max/Swift-4'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'MealTrackingPilotTests' do
    inherit! :search_paths
    pod 'Nimble'
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

  target 'MealTrackingPilotUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      config.build_settings['SWIFT_VERSION'] = '4.0'
    end
  end
end
